name: tests
on:
  push:
    branches-ignore:
      - deploy
    tags-ignore:
      - "*"

concurrency:
  group: paddle-integration-mongodb-tests

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]

    steps:
    - name: Git checkout
      uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - name: test
      run: ./test.sh
      env:
        NODE_ENV: ci